import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`pt-[8rem] bg-[#f3f3f3] ${inter.className}`}>
        <Providers>
            <Navbar/>
            {children}
            <Footer/>
        </Providers>
      </body>
    </html>
  );
}
